app_name: EnrichTransactionStream

kafka:
  brokers: kafka:29092
  topics:
    users: users
  starting_offsets: earliest

schema:
  user_schema_path: resources/schemas/user_event.schema.json

output:
  mode: append
  truncate: false
