app_name: EnrichTransactionStream

kafka:
  brokers: kafka:29092
  topics:
    transactions: pos_transactions
    users: users_topic
  starting_offsets: latest

schema:
  transaction_schema_path: resources/schemas/transaction_event.schema.json
  user_schema_path: resources/schemas/user_event.schema.json

output:
  mode: console
  truncate: false
