version: "3.8"

services:
  spark-master:
    image: bitnami/spark:3.3.0
    platform: linux/amd64
    container_name: spark-master
    environment:
      - SPARK_MODE=master
    ports:
      - "7077:7077"
      - "8080:8080"
    networks:
      - kafka_net

  spark-worker-1:
    image: bitnami/spark:3.3.0
    platform: linux/amd64
    container_name: spark-worker-1
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    ports:
      - "8081:8081"
    networks:
      - kafka_net

  spark-submit-job:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
    container_name: spark-submit-job
    depends_on:
      - spark-master
      - spark-worker-1
    networks:
      - kafka_net
    command: >
      /opt/bitnami/spark/bin/spark-submit
      --master spark://spark-master:7077
      --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.3.0,org.apache.kafka:kafka-clients:2.8.0
      /app/streaming_jobs/enrich_transaction.py

networks:
  kafka_net:
    external: true  # 🔥 This allows connecting to your existing Kafka network
