version: "3.8"

services:
  spark-master:
    image: bitnami/spark:3.3.0
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
    ports:
      - "7077:7077"   # Spark master port
      - "8080:8080"   # Spark master web UI
    networks:
      - kafka_net

  spark-worker-1:
    image: bitnami/spark:3.3.0
    container_name: spark-worker-1
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    ports:
      - "8081:8081"   # Spark worker web UI
    networks:
      - kafka_net

  spark-worker-2:
    image: bitnami/spark:3.3.0
    container_name: spark-worker-2
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    ports:
      - "8082:8082"
    networks:
      - kafka_net

networks:
  kafka_net:
    external: true
